# Generated by Django 6.0.6 on 2026-06-20 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='linked_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.aireport'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
